version: "3.9"

volumes:
  corpora_data:
    external: false

services:
  api:
    container_name: api

  web:
    container_name: web

  postgres:
    container_name: postgres

  nginx:
    container_name: nginx_label_studio

  app:
    container_name: app_label_studio