# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY ../web/package.json ./
COPY ../web/package-lock.json ./
RUN npm install
RUN npm install react-scripts@3.4.1 -g
RUN npm install react@^18.0.0 react-dom@^18.0.0 @mui/material @emotion/react @emotion/styled

# add app
COPY ../web ./

# start app
CMD ["npm", "start"]